version: "3.5"

services:
  metax-1:
    build: ./
    ports:
      - 8001:3000
    command: [ "./start.sh" ]
    volumes:
      - ./metax-1:/metax-data
  metax-2:
    build: ./
    ports:
      - 8002:3000
    command: [ "./start.sh" ]
    volumes:
      - ./metax-2:/metax-data
  metax-3:
    build: ./
    ports:
      - 8003:3000
    command: [ "./start.sh" ]
    volumes:
      - ./metax-3:/metax-data